surikat_booking_homepage:
    path:     /
    defaults: { _controller: SurikatBookingBundle:Home:index }

_booking:
    path:     /booking
    defaults: { _controller: SurikatBookingBundle:Booking:Booking }

_new_booking:
    path:     /booking/new/{code}
    defaults: { _controller: SurikatBookingBundle:Booking:NewBooking }

_show:
    path:     /booking/show
    defaults: { _controller: SurikatBookingBundle:Booking:Show }

_show_booking:
    path:     /booking/show/{code}
    defaults: { _controller: SurikatBookingBundle:Booking:ShowBooking }

_booking_availability_on:
    path:     /booking/check-availability/{date}
    defaults: { _controller: SurikatBookingBundle:Booking:CheckForAvailabiliy }

_legals:
    path:     /legals
    defaults: { _controller: SurikatBookingBundle:Home:Legals }

booking_delete:
    path:     /booking/delete/{code}
    defaults: { _controller: SurikatBookingBundle:Booking:DeleteBooking }

login:
    path: /login
    defaults:
        _controller: SurikatUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

admin_booking_setting:
    path:     /admin/setting
    defaults: { _controller: SurikatBookingBundle:Booking:ConfigBooking }
