surikat_booking_homepage:
    path:     /
    defaults: { _controller: SurikatBookingBundle:Home:index }

_booking:
    path:     /booking
    defaults: { _controller: SurikatBookingBundle:Booking:Booking }

_new_booking:
    path:     /booking/new
    defaults: { _controller: SurikatBookingBundle:Booking:NewBooking }

_new_booking_validate:
    path:     /booking/new/validate
    defaults: { _controller: SurikatBookingBundle:Booking:ValidateBooking }

_new_booking_save:
    path:     /booking/new/save
    defaults: { _controller: SurikatBookingBundle:Booking:SaveBooking }

_show:
    path:     /booking/show
    defaults: { _controller: SurikatBookingBundle:Booking:Show }

_show_booking:
    path:     /booking/show/{code}
    defaults: { _controller: SurikatBookingBundle:Booking:ShowBooking }

_booking_availability_on:
    path:     /booking/check-availability/{date}
    defaults: { _controller: SurikatBookingBundle:Booking:CheckForAvailabiliy }


admin_booking_delete:
    path:     /admin/booking/{code}
    defaults: { _controller: SurikatBookingBundle:Booking:DeleteBooking }

admin_booking_setting:
    path:     /booking/setting
    defaults: { _controller: SurikatBookingBundle:Booking:ConfigBooking }
