# src/Surikat/BookingBundle/Resources/config/services.yml

services:
    surikat_booking.availability:
       class: Surikat\BookingBundle\Service\Availability
#       arguments: ["@service_id", "plain_value", "%parameter%"]
