# src/Surikat/BookingBundle/Resources/config/services.yml

#    surikat_booking.example:
#        class: Surikat\BookingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    surikat_booking.bookingengine:
        class: Surikat\BookingBundle\Services\BookingEngine
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@surikat_booking.configmanager"

    surikat_booking.configmanager:
        class: Surikat\BookingBundle\Services\ConfigManager
        arguments:
          - "@doctrine.orm.entity_manager"

    surikat_booking.stripemanager:
        class: Surikat\BookingBundle\Services\StripeManager
        arguments:
          - "@doctrine.orm.entity_manager"

    surikat_booking.mailsenderengine:
        class: Surikat\BookingBundle\Services\MailSenderService
        arguments:
          - "@mailer"
          - "@templating"
